using System.Buffers.Binary;
using Rightpad.Receiver;
using static Rightpad.Receiver.Tests.Program;

namespace Rightpad.Receiver.Tests;

internal static class PacketDecoderTests
{
    // Independent literal fixture, not generated by the encoder below.
    private static byte[] FixedPacket() => Convert.FromHexString(
        "01020200785634122A000000" +
        "08070605040302010000C03F000010C0" +
        "FFFFFFFFFFFFFFFF000000800000803E");

    public static void FixedBytes()
    {
        byte[] bytes = FixedPacket();
        Equal(44, bytes.Length, "packet size");
        Check(PacketDecoder.TryDecode(bytes, out var packet, out string error), error);
        Equal(new PacketHeader(1, TouchEventType.Move, 2, 0x12345678, 42), packet!.Header, "header");
        Equal(0x0102030405060708UL, packet.Samples[0].TimestampNs, "nanoseconds must not be scaled");
        Equal(1.5f, packet.Samples[0].X, "x float");
        Equal(-2.25f, packet.Samples[0].Y, "y float");
        Equal(ulong.MaxValue, packet.Samples[1].TimestampNs, "unsigned timestamp range");
        Equal(int.MinValue, BitConverter.SingleToInt32Bits(packet.Samples[1].X), "negative zero bits");
        Equal(0.25f, packet.Samples[1].Y, "second y");
        Check(bytes.SequenceEqual(FixedPacket()), "decoder modified source bytes");
    }

    public static void EventTypes()
    {
        foreach (var type in new[] { TouchEventType.Down, TouchEventType.Move, TouchEventType.Up })
        {
            byte[] bytes = Encode(type, 7, 100, new TouchSample(1_234_567_890UL, -12.5f, 2048.25f));
            Check(PacketDecoder.TryDecode(bytes, out var packet, out string error), error);
            Equal(type, packet!.Header.EventType, "event mapping");
            Equal(1_234_567_890UL, packet.Samples[0].TimestampNs, "event timestampNs");
        }
    }

    public static void PreserveSamples()
    {
        TouchSample[] samples = [new(2_000_000_001UL, -0f, 9.25f),
            new(2_000_000_001UL, -0f, 9.25f), new(1_000_000_007UL, -100f, 1f)];
        Check(PacketDecoder.TryDecode(Encode(TouchEventType.Move, 1, 9, samples),
            out var packet, out string error), error);
        Check(samples.SequenceEqual(packet!.Samples), "samples were sorted, scaled or deduplicated");
        Equal(int.MinValue, BitConverter.SingleToInt32Bits(packet.Samples[0].X), "signed zero");
    }

    public static void TruncatedPackets()
    {
        byte[] packet = FixedPacket();
        for (int length = 0; length < packet.Length; length++)
            Reject(packet[..length], $"truncated at {length}");
    }

    public static void MalformedFields()
    {
        byte[] packet = FixedPacket();
        foreach (byte version in new byte[] { 0, 2, 255 })
        {
            byte[] mutated = (byte[])packet.Clone(); mutated[0] = version; Reject(mutated, "version");
        }
        foreach (byte type in new byte[] { 0, 4, 255 })
        {
            byte[] mutated = (byte[])packet.Clone(); mutated[1] = type; Reject(mutated, "event (including CANCEL)");
        }
        foreach (ushort count in new ushort[] { 0, 1, 3, ushort.MaxValue })
        {
            byte[] mutated = (byte[])packet.Clone();
            BinaryPrimitives.WriteUInt16LittleEndian(mutated.AsSpan(2), count);
            Reject(mutated, "count mismatch");
        }
        foreach (byte type in new byte[] { 1, 3 })
        {
            byte[] mutated = (byte[])packet.Clone(); mutated[1] = type; Reject(mutated, "DOWN/UP count > 1");
        }
        Reject([.. packet, 0], "trailing byte");
    }

    public static void NonFiniteCoordinates()
    {
        foreach (float value in new[] { float.NaN, float.PositiveInfinity, float.NegativeInfinity })
        foreach (int offset in new[] { 20, 24, 36, 40 })
        {
            byte[] packet = FixedPacket();
            BinaryPrimitives.WriteSingleLittleEndian(packet.AsSpan(offset), value);
            Reject(packet, "non-finite x/y");
        }
    }

    private static void Reject(byte[] bytes, string label)
    {
        Check(!PacketDecoder.TryDecode(bytes, out var packet, out string error), $"accepted {label}");
        Check(packet is null, $"partial result for {label}");
        Check(error.Length > 0, $"missing error for {label}");
    }

    // Test-only sender: there is no encoder or sender in the receiver application.
    public static byte[] Encode(TouchEventType type, uint sessionId, uint sequence, params TouchSample[] samples)
    {
        byte[] packet = new byte[12 + samples.Length * 16];
        packet[0] = 1;
        packet[1] = (byte)type;
        BinaryPrimitives.WriteUInt16LittleEndian(packet.AsSpan(2), checked((ushort)samples.Length));
        BinaryPrimitives.WriteUInt32LittleEndian(packet.AsSpan(4), sessionId);
        BinaryPrimitives.WriteUInt32LittleEndian(packet.AsSpan(8), sequence);
        for (int i = 0; i < samples.Length; i++)
        {
            int offset = 12 + i * 16;
            BinaryPrimitives.WriteUInt64LittleEndian(packet.AsSpan(offset), samples[i].TimestampNs);
            BinaryPrimitives.WriteSingleLittleEndian(packet.AsSpan(offset + 8), samples[i].X);
            BinaryPrimitives.WriteSingleLittleEndian(packet.AsSpan(offset + 12), samples[i].Y);
        }
        return packet;
    }
}
