<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Rightpad.Receiver/Rightpad.Receiver.csproj" />
    <None Update="LauncherTests.ps1" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../tools/RightpadReceiverTask.ps1" Link="RightpadReceiverTask.ps1" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
